<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title> Wage Slip - Stock Path</title>
    <link rel="stylesheet" href="wages_CSS/style.css" media="all" />
    <link href="wages_CSS/favicon.png" rel="icon" type="image/png">
  </head>
  <body>
    <header class="clearfix">
      <div id="logo">
        <img src="wages_CSS/logo.png">
      </div>
      <div id="company">

        <h2 class="name">Greens Supermarket</h2>
        <div>Plot 80 Poprtion 2,
              Bethanie Road,
              Brits, 0250</div>
        <div>+27 12 254 0224</div>
        <div><a href="mailto:company@example.com">info@greens.co.za</a></div>
      </div>
      </div>
    </header>
    <main>
      <div id="details" class="clearfix">
        <div id="client">
        <div class="name"><b>Date Generated :</b> <?php echo date("Y/m/d")?></div>
        <div class="address"><b>Time Generated :</b> <?php echo date("H:i")?></div>
        </div>
        <div id="invoice">
          <h1>WAGES REPORT</h1>
          <div class="date"><b>Generated By:</b> <?php echo $_POST["USERNAME"]?></div>
          
        </div>
      </div>
      <table border="0" cellspacing="0" cellpadding="0">
        <thead>
          <tr>
            <tr>
            <th class="desc">EMPLOYEE ID</th>
            <th class="desc">EMPLOYEE NAME</th>
           
            <th class="desc">HOURS</th>
            <th class="desc-center">WAGE TOTAL</th>
          </tr>
        </thead>
        <tbody id="tBody">
         
        </tbody>
        <tfoot>
          <tr>
            <td></td>
          
            <td colspan="2"><b>WAGE TOTAL</b></td>
            <td style="text-align: right;" ><b id="WageTotal"></b></td>
          </tr>
        </tfoot>
      </table>
      <div id="thanks"></div>
      <div id="notices">
        <div>NOTICE:</div>
        <div class="notice"> Please note that the wage slip is subject to change on collection</div>
      </div>
    </main>
    <footer>
      © 2019 Stock Path
    </footer>
    <script src="../../assets/vendor/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="JS/wageReport.js"></script>
  </body>
</html>